services:
  listings:
    build: ./listings-api
    ports:
      - "3004:3000"

  orders:
    build: ./orders-api
    ports:
      - "3002:3000"

  warehouse:
    build: ./warehouse-api
    ports:
      - "3001:3000"

  docs:
    build: ./docs-api
    ports:
      - "3003:3000"
