events {}

http {

    upstream listings {
        server listings:3000;
    }

    upstream orders {
        server orders:3000;
    }

    upstream warehouse {
        server warehouse:3000;
    }

    upstream frontend {
        server frontend:80;
    }

    upstream docs {
        server docs:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend;
        }

        location /api/ {
            proxy_pass http://listings;
        }

        location /api/orders/ {
            proxy_pass http://orders;
        }

        location /api/warehouse/ {
            proxy_pass http://warehouse;
        }

        location /docs/spec {
            proxy_pass http://listings;
        }

        location /docs/ {
            proxy_pass http://docs;
        }
    }
}
